.TH CANAIMA\-SEMILLA 7 2010\-08\-19 1.2+6 "Generador de medios vivos para Canaima GNU/Linux"

.SH NOMBRE
\fBcanaima\-semilla\fR \- Generador de medios vivos para Canaima GNU/Linux

.SH SINOPSIS
.\" FIXME
\fBcanaima\-semilla \fR\fICOMANDO\fR [\fB\-\-\ayuda\fR] [\fB\-\-uso\fR] [\fB\-\-version\fR]
.\" FIXME

.SH DESCRIPCIÓN
.\" FIXME
Canaima Semilla es un paquete que permite generar medios vivos para el sistema operativo Canaima GNU/Linux. Se le brinda a el usuario la opción de escoger la arquitectura (i386, amd64) y el medio a utilizar (USB, CD o DVD). En el futuro, éste paquete también podrá generar sistemas nVivo para los diferentes sabores de la metadistribución Canaima GNU/Linux.
.PP
El \fICOMANDO\fR es un nombre de un commando de canaima\-semilla (ver más abajo).
.\" FIXME

.SH OPCIONES
.\" FIXME
.SS Opciones comunes de canaima-semilla
Las siguientes opciones pueden ser pasadas como parámetro al comando \fBcanaima-semilla\fR.
.IP "\fB\-\-ayuda\fR" 4
Muestra la ayuda y sale.
.IP "\fB\-\-uso\fR" 4
Muestra cómo se usa y sale.
.IP "\fB\-\-version\fR" 4
Muestra la versión y sale.

.SH COMANDOS DE CANAIMA\-SEMILLA
.\" FIXME
Aqui se encuentran reflejados los comandos principales de canaima\-semilla. Por favor lee sus respectivos manuales para mayor información.
.\" FIXME

.IP "\fBcanaima\-semilla configurar\fR (man canaima-semilla-configurar)" 4
Crea el arbol de configuración en el directorio donde se ejecuta y con los parámetros indicados.
.IP "\fBcanaima\-semilla construir\fR (man canaima-semilla-construir)" 4
Construye el medio vivo basado en el arbol de configuración.
.IP "\fBcanaima-semilla limpiar\fR (man canaima-semilla-limpiar)" 4
Limpia el árbol de configuración y los archivos descargados.

.SH AUTHOR
canaima\-semilla fué desarrollado por Luis Alejandro Martínez Faneyth <lmartinez@cnti.gob.ve> para el Proyecto Canaima GNU/Linux.
