#!/bin/sh -e

DATE="$( date +%Y%m%d%H%M%S )"
LOGFILE="build.${DATE}.log"
LB_VERSION="$( dpkg-query --show --showformat='${Version}\n' live-build )"

CONFIG="${CONFIG:-${BASEDIR}/scripts/config.sh}"
LIBRARY="${LIBRARY:-${BASEDIR}/scripts/library.sh}"
VARIABLES="${VARIABLES:-${CONFDIR}/config/core}"
FUNCTIONS="${FUNCTIONS:-${BASEDIR}/scripts/functions}"
MODULES="${MODULES:-${BASEDIR}/scripts/modules}"
PROFILES="${PROFILES:-${BASEDIR}/profiles}"
SCRIPTS="${SCRIPTS:-${BASEDIR}/scripts}"
ISOS="${ISOS:-${BASEDIR}/isos}"
TEMPLATES="${TEMPLATES:-${BASEDIR}/templates}"

CS_OP_MODE="${CS_OP_MODE:-normal}"
CS_PRINT_MODE="${CS_PRINT_MODE:-normal}"

KVM_IMG="${KVM_IMG:-${ISOS}/kvm-img/c-s.img}"
KVM_DISK_MODE="${KVM_DISK_MODE:-d}"

BIN_KVM="${BIN_KVM:$( which kvm )}"
BIN_KVM_IMG="${BIN_KVM_IMG:$( which kvm-img )}"
BIN_CAT="${BIN_CAT:$( which cat )}"
BIN_DF="${BIN_DF:$( which df )}"
BIN_ECHO="${BIN_ECHO:$( which echo )}"
BIN_AWK="${BIN_AWK:$( which awk )}"
BIN_RM="${BIN_RM:$( which rm )}"
BIN_="${BIN_:$( which  )}"
BIN_="${BIN_:$( which  )}"
BIN_="${BIN_:$( which  )}"
BIN_="${BIN_:$( which  )}"
BIN_="${BIN_:$( which  )}"
BIN_="${BIN_:$( which  )}"
BIN_="${BIN_:$( which  )}"
BIN_="${BIN_:$( which  )}"
BIN_="${BIN_:$( which  )}"
BIN_="${BIN_:$( which  )}"

