#!/bin/sh -e

DATE="$( date +%Y%m%d%H%M%S )"
LOGFILE="build.${DATE}.log"
LB_VERSION="$( dpkg-query --show --showformat='${Version}\n' live-build )"

CONFIG="${CONFIG:-${BASEDIR}/scripts/config.sh}"
LIBRARY="${LIBRARY:-${BASEDIR}/scripts/library.sh}"
VARIABLES="${VARIABLES:-${CONFDIR}/config/core}"
FUNCTIONS="${FUNCTIONS:-${BASEDIR}/scripts/functions}"
MODULES="${MODULES:-${BASEDIR}/scripts/modules}"
PROFILES="${PROFILES:-${BASEDIR}/profiles}"
SCRIPTS="${SCRIPTS:-${BASEDIR}/scripts}"
ISOS="${ISOS:-${BASEDIR}/isos}"
TEMPLATES="${TEMPLATES:-${BASEDIR}/templates}"

CS_OP_MODE="${CS_OP_MODE:-normal}"
CS_PRINT_MODE="${CS_PRINT_MODE:-normal}"

KVM_IMG="${KVM_IMG:-${ISOS}/kvm-img/c-s.img}"
KVM_DISK_MODE="${KVM_DISK_MODE:-d}"

BIN_KVM="${BIN_KVM:-$( which kvm )}"
BIN_KVM_IMG="${BIN_KVM_IMG:-$( which kvm-img )}"
BIN_CAT="${BIN_CAT:-$( which cat )}"
BIN_DF="${BIN_DF:-$( which df )}"
BIN_ECHO="${BIN_ECHO:-$( which echo )}"
BIN_AWK="${BIN_AWK:-$( which awk )}"
BIN_RM="${BIN_RM:-$( which rm )}"
BIN_GETOPT="${BIN_GETOPT:-$( which getopt )}"
BIN_DPKG="${BIN_DPKG:-$( which dpkg )}"
BIN_LB="${BIN_LB:-$( which lb )}"
BIN_TEE="${BIN_TEE:-$( which tee )}"
BIN_MV="${BIN_MV:-$( which mv )}"
BIN_STAT="${BIN_STAT:-$( which stat )}"
BIN_BC="${BIN_BC:-$( which bc )}"
BIN_PRINTF="${BIN_PRINTF:-$( which printf )}"
BIN_FILE="${BIN_FILE:-$( which file )}"
BIN_IDENTIFY="${BIN_IDENTIFY:-$( which identify )}"

