#!/bin/sh

# /usr/share/canaima-semilla/hooks/canaima - script de post-intalación de canaima-semilla
# Copyright (C) 2010 Luis Alejandro Martínez Faneyth <lmartinez@cnti.gob.ve>
#

set -e

echo "*************************************"
echo "Cambiando banner del Debian Installer"
echo "*************************************"

if [ -e config/binary_debian-installer/banner.png ]
then
        TARGET_INITRD="binary/install/gtk/initrd.gz"
        REPACK_TMPDIR="binary.initrd"

	if [ -e "${TARGET_INITRD}" ]
        then
                # cpio does not have a "extract to directory", so we must change
                # directory
                mkdir -p ${REPACK_TMPDIR}
                cd ${REPACK_TMPDIR}
                gzip -d < ../${TARGET_INITRD} | cpio -i --make-directories --no-absolute-filenames

                # Overwrite banner
                cp ../config/binary_debian-installer/banner.png ./usr/share/graphics/logo_debian.png
		cp ../config/binary_debian-installer-includes/gtkrc ./usr/share/themes/Clearlooks/gtk-2.0/gtkrc


                find | cpio -H newc -o | gzip -9 > ../${TARGET_INITRD}
                cd ..
                rm -rf ${REPACK_TMPDIR}
        fi
fi
