#!/bin/sh

# /usr/share/canaima-semilla/hooks/minimal - hook list for live-helper(7)
# Copyright (C) 2006-2010 Daniel Baumann <daniel@debian.org>
#
# live-helper comes with ABSOLUTELY NO WARRANTY; for details see COPYING.
# This is free software, and you are welcome to redistribute it
# under certain conditions; see COPYING for details.

set -e

# Removing unused files
find . -name *~ -print0 | xargs -0 rm -f

rm -rf /var/cache/man/*

# Truncating logs
for FILE in $(find /var/log/ -type f)
do
	: > ${FILE}
done
